### ISSUE TITLE
Errors when auctioning spawners

### ISSUE THREAD

**Issue by IceString3** [virustotalop/ObsidianAuctions#16]
An error happens when I try to auction a mob spawner

[StarDan90: Given [Monster Spawner] * 1 to StarDan90]
[16:58:47 INFO]: StarDan90 issued server command: /auc
[16:58:54 INFO]: StarDan90 issued server command: /auc start
[16:58:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'auc' in plugin ObsidianAuctions v4.1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.virustotal.floauction.utility.MaterialUtil.getSpawnerType(MaterialUtil.java:119) ~[?:?]
	at me.virustotal.floauction.utility.MaterialUtil.getName(MaterialUtil.java:46) ~[?:?]
	at com.flobi.floauction.utilities.Items.getItemName(Items.java:694) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.parseMessageTokens(AuctionMessageManager.java:413) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.parseMessages(AuctionMessageManager.java:327) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.sendMessage(AuctionMessageManager.java:181) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.broadcastAuctionMessage(AuctionMessageManager.java:134) ~[?:?]
	at com.flobi.floauction.Auction.info(Auction.java:324) ~[?:?]
	at com.flobi.floauction.Auction.start(Auction.java:283) ~[?:?]
	at com.flobi.floauction.AuctionScope.checkThisAuctionQueue(AuctionScope.java:273) ~[?:?]
	at com.flobi.floauction.AuctionScope.checkAuctionQueue(AuctionScope.java:426) ~[?:?]
	at com.flobi.floauction.AuctionScope.queueAuction(AuctionScope.java:215) ~[?:?]
	at com.flobi.floauction.FloAuction.onCommand(FloAuction.java:918) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 15 more

When I try to auction the spawner again, it shows a different error:
[16:59:32 INFO]: StarDan90 issued server command: /auc start
[16:59:38 WARN]: [ObsidianAuctions] Task #17 for ObsidianAuctions v4.1.0 generated an exception
java.lang.NullPointerException
	at me.virustotal.floauction.utility.MaterialUtil.getSpawnerType(MaterialUtil.java:119) ~[?:?]
	at me.virustotal.floauction.utility.MaterialUtil.getName(MaterialUtil.java:46) ~[?:?]
	at com.flobi.floauction.utilities.Items.getItemName(Items.java:694) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.parseMessageTokens(AuctionMessageManager.java:413) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.parseMessages(AuctionMessageManager.java:327) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.sendMessage(AuctionMessageManager.java:181) ~[?:?]
	at com.flobi.floauction.AuctionMessageManager.broadcastAuctionMessage(AuctionMessageManager.java:134) ~[?:?]
	at com.flobi.floauction.Auction.info(Auction.java:324) ~[?:?]
	at com.flobi.floauction.Auction.start(Auction.java:283) ~[?:?]
	at com.flobi.floauction.AuctionScope.checkThisAuctionQueue(AuctionScope.java:273) ~[?:?]
	at com.flobi.floauction.AuctionScope.checkAuctionQueue(AuctionScope.java:426) ~[?:?]
	at com.flobi.floauction.FloAuction$2.run(FloAuction.java:413) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

Server version is paperspigot 1.8.8
The error doesn't happen on a 1.10 server

**Comment by virustotalop** [comment]
Are you running the latest version that is available? I am unable to reproduce the bug on a 1.8.8 paperspigot server. Can you send me a list of your plugins?

**Comment by IceString3** [comment]
WorldEdit, Skript, WildSkript, GroupManager, iConomy, PlugMan, ViaVersion, SkQuery, TuSKe, Vault, WorldGuard, skRayFall, ObsidianAuctions

Yes, I'm using the latest available 1.8.8 paperspigot (build 443)

**Comment by virustotalop** [comment]
Are you running the latest build of obsidian auctions?

**Comment by IceString3** [comment]
Yes, the latest build on spigot

**Comment by virustotalop** [comment]
Can you send me a player dat file of someone who has a spawner in their inventory?

**Comment by IceString3** [comment]
[StarDan90_data.zip](https://github.com/virustotalop/ObsidianAuctions/files/569509/StarDan90_data.zip)

I tried giving myself spawners using EssentialsX and they can be auctioned. However, the generic mob spawner throws errors when auctioned. (the one that can be given using /give)
In that player.dat file I have the generic mob spawner.

**Comment by virustotalop** [comment]
It doesn't seem that by default the server writes any nbt tags that would make you able to auction different spawner types. I will just make it fail gracefully and default to say a pig spawner is being auctioned since the only thing that can be spawned with vanilla spawners is pigs anyways.

**Comment by virustotalop** [comment]
This isn't relevant anymore since I rewrote the language system. Superseded by #75
