### ISSUE TITLE
null pointer (mob eggs)

### ISSUE THREAD

**Issue by PhanaticD** [virustotalop/ObsidianAuctions#17]
the following spams console forever till a restart
```
[09:57:00] [Server thread/WARN]: [ObsidianAuctions] Task #79 for ObsidianAuctions v4.1.1 generated an exception
java.lang.NullPointerException
    at me.virustotal.floauction.utility.MaterialUtil.getMobEggType(MaterialUtil.java:94) ~[?:?]
    at me.virustotal.floauction.utility.MaterialUtil.getName(MaterialUtil.java:41) ~[?:?]
    at com.flobi.floauction.utilities.Items.getItemName(Items.java:694) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.parseMessageTokens(AuctionMessageManager.java:408) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.parseMessages(AuctionMessageManager.java:322) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.sendMessage(AuctionMessageManager.java:182) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.broadcastAuctionMessage(AuctionMessageManager.java:135) ~[?:?]
    at com.flobi.floauction.Auction.info(Auction.java:324) ~[?:?]
    at com.flobi.floauction.Auction.start(Auction.java:283) ~[?:?]
    at com.flobi.floauction.AuctionScope.checkThisAuctionQueue(AuctionScope.java:273) ~[?:?]
    at com.flobi.floauction.AuctionScope.checkAuctionQueue(AuctionScope.java:426) ~[?:?]
    at com.flobi.floauction.FloAuction$2.run(FloAuction.java:408) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916.2]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[09:57:01] [Server thread/INFO]: OTTO_007 issued server command: /auc 1 1900 100

```
```
[09:58:56] [Server thread/WARN]: [ObsidianAuctions] Task #6321549 for ObsidianAuctions v4.1.1 generated an exception
java.lang.NullPointerException
    at me.virustotal.floauction.utility.MaterialUtil.getMobEggType(MaterialUtil.java:94) ~[?:?]
    at me.virustotal.floauction.utility.MaterialUtil.getName(MaterialUtil.java:41) ~[?:?]
    at com.flobi.floauction.utilities.Items.getItemName(Items.java:694) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.parseMessageTokens(AuctionMessageManager.java:408) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.parseMessages(AuctionMessageManager.java:322) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.sendMessage(AuctionMessageManager.java:182) ~[?:?]
    at com.flobi.floauction.AuctionMessageManager.broadcastAuctionMessage(AuctionMessageManager.java:135) ~[?:?]
    at com.flobi.floauction.Auction.end(Auction.java:408) ~[?:?]
    at com.flobi.floauction.Auction$1.run(Auction.java:261) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916.2]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by virustotalop** [comment]
Can you give me a screenshot of /pl?

**Comment by virustotalop** [comment]
Fixed due to the rewrite of the language system
