### ISSUE TITLE
Bunch of errors in console

### ISSUE THREAD

**Issue by alexp9982** [virustotalop/ObsidianAuctions#4]
http://pastebin.com/d4YrU0F8

**Comment by alexp9982** [comment]
This occurred on CraftBukkit 1.9.4

**Comment by virustotalop** [comment]
Can you give me the output of /ver? I am attempting to reproduce this on CraftBukkit 1.9.4 and I cannot. I see that the getClickedInventory method is removed in 1.9.4 according to the javadocs but it seems to be working just fine.

**Comment by alexp9982** [comment]
[19:56:00] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
[19:56:00] [Server thread/INFO]: Checking version, please wait...
[19:56:04] [Thread-16/INFO]: You are 77 version(s) behind

**Comment by virustotalop** [comment]
Alright I am going to go ahead and push a commit to fix this. Testing it with 1.10 CraftBukkit shows the method doesn't exist but my 1.9.4 CraftBukkit jar does not. I can upload a test release build if you want so you can test it out.

**Comment by alexp9982** [comment]
I would love to!

**Comment by alexp9982** [comment]
So it will work with 1.9.4?

**Comment by virustotalop** [comment]
It should work with 1.9.4, making a new build now.

**Comment by alexp9982** [comment]
Ok, thanks so much for a pretty quick response

**Comment by virustotalop** [comment]
Before I push out the commit this new build works, going to upload it as a release.

**Comment by alexp9982** [comment]
When will that be uploaded to Spigot?

**Comment by virustotalop** [comment]
It will be uploaded to spigot later, I have some other features to test before I do my next release. If you want you can test the pre-release here. https://github.com/virustotalop/ObsidianAuctions/releases/tag/4.0.2

**Comment by alexp9982** [comment]
I will start testing right away!

**Comment by virustotalop** [comment]
Alright, sounds great.

**Comment by virustotalop** [comment]
If the build doesn't work paste any relevant errors here. I have some plans to attend to.

**Comment by alexp9982** [comment]
Seems to be working fine for now

**Comment by virustotalop** [comment]
Alright, sounds great.

**Comment by virustotalop** [comment]
Have you ran into any issues?

**Comment by virustotalop** [comment]
Is this issue fixed? I'm guessing it is. For now I am going to go ahead and flag it as fixed.

**Comment by alexp9982** [comment]
Sorry for not answering and I believe the issue IS fixed. However I will alert you if I run into any other issues. Thank you so much for helping me out.

**Comment by virustotalop** [comment]
Alright thank you, if you run into any issues feel free to file another issue. I am going to go ahead and close this.

**Comment by alexp9982** [comment]
Still get errors, after some players joined my server

**Comment by virustotalop** [comment]
Can you post the stacktraces?

**Comment by alexp9982** [comment]
What are those?

**Comment by alexp9982** [comment]
And where can I find them?

**Comment by virustotalop** [comment]
I am referring to the errors you get in the console. You said you were still getting errors.

**Comment by alexp9982** [comment]
I will get them shortly

**Comment by alexp9982** [comment]
Could not pass event InventoryCreativeEvent to ObsidianAuctions v4.1.0
org.bukkit.event.EventException
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1937)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:23)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:9)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
me.virustotal.floauction.listeners.InventoryClickListener.invClick(InventoryClickListener.java:14)
~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
... 15 more
[17:24:18] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 20 seconds!
[17:24:23] [Server thread/ERROR]: Could not pass event
InventoryCreativeEvent to ObsidianAuctions v4.1.0
org.bukkit.event.EventException
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1937)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:23)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInSetCreativeSlot.a(SourceFile:9)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
me.virustotal.floauction.listeners.InventoryClickListener.invClick(InventoryClickListener.java:14)
~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
... 15 more
[17:24:28] [Server thread/INFO]: Michael82476 issued server command: /i
playerskull 1
[17:24:38] [Server thread/INFO]: [PreciousMedals] Removed 0 Entities!
[17:24:47] [pool-3-thread-19/WARN]: Exception in thread "pool-3-thread-19"
[17:24:47] [pool-3-thread-19/WARN]:
org.apache.commons.lang.UnhandledException: Plugin BuycraftX v10.1.3
generated an exception while executing task 130
at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at net.buycraft.plugin.bukkit.tasks.SignUpdater.run(SignUpdater.java:54)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:53)
at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

[17:24:52] [Netty Epoll Server IO #5/INFO]: a[Owner]a Michael82476: Alex
[17:25:00] [Netty Epoll Server IO #5/INFO]: a[Owner]a Michael82476: This is
the Most Recent Donator Station.
[17:27:02] [pool-3-thread-21/INFO]: [BuycraftX] Fetching all due players...
[17:27:03] [pool-3-thread-21/INFO]: [BuycraftX] Fetched due players (0
found).
[17:31:18] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 60 seconds!
[17:31:58] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 20 seconds!
[17:32:03] [pool-3-thread-33/INFO]: [BuycraftX] Fetching all due players...
[17:32:05] [pool-3-thread-33/INFO]: [BuycraftX] Fetched due players (0
found).
[17:32:18] [Server thread/INFO]: [PreciousMedals] Removed 0 Entities!
[17:37:03] [Server thread/INFO]: CONSOLE issued server command: /list
[17:37:03] [Server thread/INFO]: There are 2 out of maximum 30 players
online.
[17:37:03] [Server thread/INFO]: Players: a[Owner]a alexp9982, a[Owner]a
Michael82476
[17:37:05] [pool-3-thread-34/INFO]: [BuycraftX] Fetching all due players...
[17:37:05] [pool-3-thread-34/INFO]: [BuycraftX] Fetched due players (0
found).
[17:38:58] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 60 seconds!
[17:39:38] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 20 seconds!
[17:39:58] [Server thread/INFO]: [PreciousMedals] Removed 0 Entities!
[17:42:05] [pool-3-thread-34/INFO]: [BuycraftX] Fetching all due players...
[17:42:06] [pool-3-thread-34/INFO]: [BuycraftX] Fetched due players (0
found).
[17:46:01] [Server thread/INFO]: alexp9982 issued server command: /ncp
reload
[17:46:01] [Server thread/INFO]: [NoCheatPlus] §cNCP: §fReloading
configuration...
[17:46:01] [Server thread/INFO]: [NoCheatPlus] McAccess set to: 1.9.4 /
Spigot-CB-1.9_R2
[17:46:01] [Server thread/INFO]: [NoCheatPlus] §cNCP: §fConfiguration
reloaded.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added block-info for
Minecraft 1.5 blocks.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added block-info for
Minecraft 1.6.1 blocks.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added block-info for
Minecraft 1.7.2 blocks.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added block-info for
Minecraft 1.8 blocks.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added block-info for
Minecraft 1.9 blocks.
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Removed hook:
AllViolations(NCP) [1.0].
[17:46:01] [pool-3-thread-34/INFO]: [NoCheatPlus] Added hook:
AllViolations(NCP) [1.0].
[17:46:38] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 60 seconds!
[17:47:06] [pool-3-thread-55/INFO]: [BuycraftX] Fetching all due players...
[17:47:07] [pool-3-thread-55/INFO]: [BuycraftX] Fetched due players (0
found).
[17:47:18] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 20 seconds!
[17:47:38] [Server thread/INFO]: [PreciousMedals] Removed 0 Entities!
[17:51:23] [User Authenticator #3/INFO]: UUID of player Dojouz is
def47dcc-b717-4875-a9cd-bb14c284af29
[17:51:23] [Server thread/INFO]: Dojouz[/72.94.168.81:61661] logged in with
entity id 367140 at ([world]1754.5, 82.0, -1027.5)
[17:51:23] [Server thread/INFO]: + Dojouz
[17:51:23] [pool-3-thread-55/INFO]: [GAListener] Player: Dojouz has 0 votes
[17:51:30] [Netty Epoll Server IO #29/INFO]: [Builder] [Trial-Mod] Dojouz:
Hello
[17:51:39] [Netty Epoll Server IO #4/INFO]: a[Owner]a alexp9982: HI!
[17:51:44] [Netty Epoll Server IO #4/INFO]: a[Owner]a alexp9982: We are
setting up buycraft
[17:51:46] [Server thread/INFO]: alexp9982 issued server command: /buy
[17:51:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent
to ObsidianAuctions v4.1.0
org.bukkit.event.EventException
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1789)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
me.virustotal.floauction.listeners.InventoryClickListener.invClick(InventoryClickListener.java:14)
~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
... 15 more
[17:51:49] [Server thread/ERROR]: Could not pass event InventoryClickEvent
to ObsidianAuctions v4.1.0
org.bukkit.event.EventException
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1789)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
me.virustotal.floauction.listeners.InventoryClickListener.invClick(InventoryClickListener.java:14)
~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
... 15 more
[17:51:49] [Netty Epoll Server IO #29/INFO]: [Builder] [Trial-Mod] Dojouz:
Sweet
[17:52:01] [Netty Epoll Server IO #29/INFO]: [Builder] [Trial-Mod] Dojouz:
If you could tp me to the arenas I can continue working on it.
[17:52:07] [pool-3-thread-59/INFO]: [BuycraftX] Fetching all due players...
[17:52:09] [pool-3-thread-59/INFO]: [BuycraftX] Fetched due players (0
found).
[17:52:26] [Server thread/INFO]: Dojouz issued server command: /spawn
[17:52:48] [Netty Epoll Server IO #29/INFO]: [Builder] [Trial-Mod] Dojouz:
Brb
[17:52:49] [Server thread/INFO]: - Dojouz
[17:53:41] [User Authenticator #4/INFO]: UUID of player Dojouz is
def47dcc-b717-4875-a9cd-bb14c284af29
[17:53:41] [Server thread/INFO]: Dojouz[/72.94.168.81:61719] logged in with
entity id 396175 at ([world]1754.5, 82.0, -1027.5)
[17:53:41] [pool-3-thread-58/INFO]: [GAListener] Player: Dojouz has 0 votes
[17:53:41] [Server thread/INFO]: + Dojouz
[17:54:07] [Server thread/INFO]: Dojouz issued server command: /afk
[17:54:18] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 60 seconds!
[17:54:58] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 20 seconds!
[17:55:18] [Server thread/INFO]: [PreciousMedals] Removed 0 Entities!
[17:56:20] [Server thread/INFO]: alexp9982 issued server command: /buy
[17:56:28] [Server thread/INFO]: alexp9982 issued server command: /mv tp
partygames
[17:56:37] [Server thread/INFO]: alexp9982 issued server command: /tp
Dojouz alexp9982
[17:56:38] [Server thread/INFO]: alexp9982 issued server command: /spawn
[17:56:45] [Server thread/INFO]: alexp9982 issued server command: /spawn
[17:56:46] [Server thread/INFO]: alexp9982 issued server command: /tp
Dojouz alexp9982
[17:56:51] [Server thread/INFO]: alexp9982 issued server command: /mv tp
partygames
[17:56:58] [Server thread/INFO]: alexp9982 issued server command: /tp
Dojouz alexp9982
[17:57:02] [Server thread/INFO]: alexp9982 issued server command: /gmc
Dojouz
[17:57:07] [Server thread/INFO]: CONSOLE issued server command: /list
[17:57:07] [Server thread/INFO]: There are 3 out of maximum 30 players
online.
[17:57:07] [Server thread/INFO]: Players: [AFK][Builder] [Trial-Mod]
Dojouz, a[Owner]a alexp9982, a[Owner]a Michael82476
[17:57:09] [pool-3-thread-58/INFO]: [BuycraftX] Fetching all due players...
[17:57:10] [pool-3-thread-58/INFO]: [BuycraftX] Fetched due players (0
found).
[17:58:57] [Server thread/INFO]: alexp9982 issued server command: /buy
[17:59:00] [Server thread/ERROR]: Could not pass event InventoryClickEvent
to ObsidianAuctions v4.1.0
org.bukkit.event.EventException
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1789)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[?:1.8.0_101]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[CraftBukkit194.jar:git-Bukkit-0cd0397]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError:
org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
at
me.virustotal.floauction.listeners.InventoryClickListener.invClick(InventoryClickListener.java:14)
~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_101]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
~[CraftBukkit194.jar:git-Bukkit-0cd0397]
... 15 more
[18:01:58] [Server thread/INFO]: [PreciousMedals] Warning, Ground items
will be removed in 60 seconds!
[18:02:00] [pool-3-thread-67/WARN]: Exception in thread "pool-3-thread-67"
[18:02:00] [pool-3-thread-67/WARN]:
org.apache.commons.lang.UnhandledException: Plugin BuycraftX v10.1.3
generated an exception while executing task 36
at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at net.buycraft.plugin.bukkit.tasks.SignUpdater.run(SignUpdater.java:54)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:53)
at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by alexp9982** [comment]
Ignore the buycraft error at the bottom, sorry

**Comment by virustotalop** [comment]
Should be fixed as of the latest commit. I will be releasing that build publicly soon.

**Comment by virustotalop** [comment]
The newest build is now out, it should resolve the issue you are having.
